[package]
name = "nisaba"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

description = "Data quality, reconciliation, and validation across different data stores"
repository = "https://github.com/realonbebeto/nisaba"
keywords = [
    "dataframe",
    "schema-engine",
    "schema",
    "data-validation",
    "data-reconciliation",
    "data-quality",
]
authors = ["Bebeto Nyamwamu. (realonbebeto) <realonbbt@gmail.com>"]
categories = [
    "data-processing",
    "data-validation",
    "schema-management",
    "data-engineering",
    "data",
]

[dependencies]
anyhow = "1.0.100"
arrow = { version = "56.2.0", features = ["csv", "json"] }
arrow-odbc = "21.0.0"
dirs = "6.0.0"
fastembed = "5.4.0"
futures = "0.3.31"
lancedb = "0.23.0"
mongodb = "3.4.1"
nalgebra = "0.34.1"
parquet = "56.2.0"
rand = { version = "0.9.2", features = ["std_rng"] }
rand_distr = "0.5.1"
regex = "1.12.2"
thiserror = "2.0.17"
uuid = { version = "1.19.0", features = ["v7"], default-features = false }
