[graph]
exclude-unpublished = true

[advisories]
unmaintained = "none"
ignore = ["RUSTSEC-2023-0071", "RUSTSEC-2026-0002"]


[licenses]
confidence-threshold = 0.8
allow = ["MIT", "Apache-2.0", "Zlib"]


[bans]
multiple-versions = "deny"
highlight = "all"
skip-tree = [
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
    { name = "zune-jpeg" },
]
